### PR TITLE
fix: content pay

### PR DESCRIPTION
**Pull request by RiXelanya**
## Describe your changes
Fix pay_content
Change Test pay_content_with_myria , pay_content_with_assets , pay_content_with_escrow
already built for release
already tested using cargo test pay_content 
3 test successful, 1 failed
pay_content_with_insufficient_balance failed
Change has been commented

### CODE REVIEW

**Comment by RiXelanya** [comment]
[13/03/2023 16:52 ] Update to test.rs now test on cant_pay_content_when_insufficient_balance has been fixed by changing amount from 20 to 22

**Comment by irmannmal** [comment]
Please fix the failed test @RiXelanya

**Comment by RiXelanya** [comment]
Ready for workflow test

**Comment by irmannmal** [comment]
run this bash script on your local
```
./.maintain/fix-lint-and-format.sh
```

**Comment by irmannmal** [comment]
Please review mas @abdulhakim2902

**Review by abdulhakim2902 — APPROVED** [review]

**Comment by irmannmal** [comment]
LGTM, i'll merge this, please make new PR for update runtime version and package version @RiXelanya @abdulhakim2902

**Pull request merged**
